const rosters = [
  {
    game: "Apex Legends",
    team: [
      {
        name: "TANNER TREBB",
        nickname: "ROGUE",
        img_url: "./images/ROGUE.png",
        twitter_url: "twitter.com/TTrebb",
        twitch_url: "twitch.tv/rogue/",
      },
      {
        name: "NATHAN NGUYEN",
        nickname: "NAFEN",
        img_url: "./images/NAFEN.png",
        twitter_url: "twitter.com/nafengg",
        twitch_url: "twitch.tv/nafengg",
      },
      {
        name: "LULULUVELY",
        nickname: "",
        img_url: "./images/LULULUVELY.png",
        twitter_url: "twitter.com/LuluLuvely",
        twitch_url: "twitch.tv/lululuvely",
      },
      {
        name: "AIDAN GRODIN",
        nickname: "ROCKER",
        img_url: "./images/ROCKER.png",
        twitter_url: "twitter.com/rockerapex",
        twitch_url: "twitch.tv/rockerapex",
      },
    ],
    game_img: "./images/apex_legends.png",
  },
  {
    game: "Call of Duty",
    team: [
      {
        name: "Seth Abner",
        nickname: "Scump",
        img_url: "./images/Scump.png",
        twitter_url: "twitter.com/scump",
        twitch_url: "twitch.tv/scump",
        youtube_url: "youtube.com/Scumperjumper",
      },
      {
        name: "Matthew Piper",
        nickname: "FormaL",
        img_url: "./images/FormaL.png",
        twitter_url: "twitter.com/FormaL",
        twitch_url: "twitch.tv/formal",
        youtube_url: "youtube.com/user/FormaLCoD",
      },
      {
        name: "Brandon Otell",
        nickname: "Dashy",
        img_url: "./images/Dashy.png",
        twitter_url: "twitter.com/DashySZN",
        twitch_url: "twitch.tv/Dashy",
        youtube_url: "youtube.com/dashy",
      },
      {
        name: "Dylan Hannon",
        nickname: "Envoy",
        img_url: "./images/Envoy.png",
        twitter_url: "twitter.com/DylanEnvoy",
        twitch_url: "twitch.tv/DylanEnvoy",
        youtube_url: "",
      },
      {
        name: "Nick Kershner",
        nickname: "MaNiaC",
        img_url: "./images/MaNiaC.png",
        twitter_url: "twitter.com/OpTicMaNiaC",
        twitch_url: "",
        youtube_url: "youtube.com/ManiacYT",
      },
      {
        name: "Jordon General",
        nickname: "General",
        img_url: "./images/General.png",
        twitter_url: "twitter.com/JordonGeneral",
        twitch_url: "twitch.tv/JordonGeneral",
        youtube_url: "youtube.com/JordonHollywood1",
      },
      {
        name: "Troy Michaels",
        nickname: "Sender",
        img_url: "./images/Sender.png",
        twitter_url: "twitter.com/Sender_FN",
        twitch_url: "twitch.tv/Sender",
        youtube_url: "youtube.com/MLGSender",
      },
      {
        name: "Marcus Blanks",
        nickname: "MBoZe",
        img_url: "./images/MBoZe.png",
        twitter_url: "twitter.com/BoZe",
        twitch_url: "twitch.tv/mboze",
        youtube_url: "youtube.com/MBoZeYT",
      },
      {
        name: "Will Johnson",
        nickname: "BigTymeR",
        img_url: "./images/BigTymeR.png",
        twitter_url: "twitter.com/OpTic_BigTymeR",
        twitch_url: "twitch.tv/BigTymeR",
        youtube_url: "youtube.com/OpTicBigTymeR",
      },
      {
        name: "Jordan Thomas",
        nickname: "HusKerrs",
        img_url: "./images/HusKerrs.png",
        twitter_url: "twitter.com/HusKerrs",
        twitch_url: "twitch.tv/huskerrs",
        youtube_url: "youtube.com/HusKerrs",
      },
    ],
    game_img: "./images/call_of_duty.png",
  },
  {
    game: "Fortnite",
    team: [
      {
        name: "BENJYFISHY",
        nickname: "",
        img_url: "./images/BENJYFISHY.png",
        twitter_url: "twitter.com/benjyfishy",
        twitch_url: "twitch.tv/benjyfishy",
        youtube_url: "",
      },
      {
        name: "CLIX",
        nickname: "",
        img_url: "./images/CLIX.png",
        twitter_url: "twitter.com/ClixHimself",
        twitch_url: "twitch.tv/Clix",
        youtube_url: "",
      },
      {
        name: "RONALDO",
        nickname: "",
        img_url: "./images/RONALDO.png",
        twitter_url: "twitter.com/StableRonaldo",
        twitch_url: "twitch.tv/stableronaldo_",
        youtube_url: "",
      },
      {
        name: "EPIKWHALE",
        nickname: "",
        img_url: "./images/EPIKWHALE.png",
        twitter_url: "twitter.com/EpikWhale",
        twitch_url: "twitch.tv/epikwhale",
        youtube_url: "",
      },
      {
        name: "ZAYT",
        nickname: "",
        img_url: "./images/ZAYT.png",
        twitter_url: "twitter.com/Zayt",
        twitch_url: "twitch.tv/zayt",
        youtube_url: "",
      },
      {
        name: "EDGEY",
        nickname: "",
        img_url: "./images/EDGEY.png",
        twitter_url: "twitter.com/Edgeyy",
        twitch_url: "twitch.tv/edgeyy",
        youtube_url: "",
      },
    ],
    game_img: "./images/fortnite.png",
  },
  {
    game: "Rocket League",
    team: [
      {
        name: "Garrett Gordon",
        nickname: "GarrettG",
        img_url: "./images/GarrettG.png",
        twitter_url: "twitter.com/GarrettG",
        twitch_url: "twitch.tv/garrettg",
        youtube_url: "youtube.com/c/GarrettG",
      },
      {
        name: "Justin Morales",
        nickname: "jstn.",
        img_url: "./images/jstn.png",
        twitter_url: "twitter.com/Its_JSTN",
        twitch_url: "twitch.tv/ItsJSTN",
        youtube_url: "",
      },
      {
        name: "Mariano Arruda",
        nickname: "SquishyMuffinz",
        img_url: "./images/SquishyMuffinz.png",
        twitter_url: "twitter.com/SquishyMuffinz",
        twitch_url: "twitch.tv/squishymuffinz",
        youtube_url: "youtube.com/SquishyMuffinz",
      },
      {
        name: "Emiliano Benny",
        nickname: "Sizz",
        img_url: "./images/sizz.png",
        twitter_url: "https://twitter.com/Sizz",
        twitch_url: "twitch.tv/Sizz",
        youtube_url: "",
      },
      {
        name: "Wyatt MUSTY",
        nickname: "amustycow",
        img_url: "./images/amustycow.png",
        twitter_url: "twitter.com/amustycow",
        twitch_url: "twitch.tv/amustycow",
        youtube_url: "youtube.com/amustycow",
      },
      {
        name: "Joni Humaloja",
        nickname: "JZR",
        img_url: "./images/JZR.png",
        twitter_url: "twitter.com/nrg_jzr",
        twitch_url: "twitch.tv/nrg_jzr",
        youtube_url: "youtube.com/user/JHZER",
      },
    ],
    game_img: "./images/rocket-league.png",
  },
  {
    game: "Valorant",
    team: [
      {
        name: "DAMIAN STEELE",
        nickname: "DAPS",
        img_url: "./images/Daps.png",
        twitter_url: "twitter.com/daps",
        twitch_url: "twitch.tv/daps",
        youtube_url: "",
      },
      {
        name: "SAM OH",
        nickname: "S0M",
        img_url: "./images/S0M.png",
        twitter_url: "twitter.com/s0mcs",
        twitch_url: "twitch.tv/s0mcs",
        youtube_url: "",
      },
      {
        name: "BRANDON WINN",
        nickname: "ACEU",
        img_url: "./images/ACEU.png",
        twitter_url: "twitter.com/acesu",
        twitch_url: "twitch.tv/aceu",
        youtube_url: "",
      },
      {
        name: "Bradley Fodor",
        nickname: "ANDROID",
        img_url: "./images/ANDROID.png",
        twitter_url: "https://twitter.com/androidx23",
        twitch_url: "https://www.twitch.tv/androidx",
        youtube_url: "",
      },
    ],
    game_img: "./images/valorant.png",
  },
];

export default rosters;
